### ISSUE TITLE
Duplicate properties for .row block

### ISSUE THREAD

**Issue by davidknezic** [axa-ch/style-guide#402]
Strangely, the implementation of our `.row` block looks like this:

```less
@import '../mixins/make-row';

.row {
  .make-row();

  display: flex;
  flex-wrap: wrap;

  margin-left: (@grid-gutter-width / -2);
  margin-right: (@grid-gutter-width / -2);
}
```

The last four properties are exactly the same inside the `make-row` mixin. We should remove this duplication.
