### ISSUE TITLE
content of media-queries is always output two times

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#484]
Our `.response` mixin is buggy, as it outputs all media-queries for breakpoints `large`, `small`, etc. two times. consider the following code.

```less
.foo {
  .respond(large, {
    display: block;
  });
}
```

compiles to:

```css
@media (max-width: large) {
  .foo {
    display: block;
  }
}

@media (max-width: 960px) {
  .foo {
    display: block;
  }
}
```

This is because of less's mixin pattern matching feature: http://lesscss.org/features/#mixins-parametric-feature-pattern-matching

I'm working on a fix with guards, we can save a lot of css by fixing that.
