### ISSUE TITLE
CSS Media Query Packing gets messed up by specifity/precendence if numbers are used

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#507]
Since we merge all of our media queries at the end with mq-packer we lose important styles because specifity/precendence gets messed up:

This is caused by two things:
* we don't use ranges (just mobile-first - `min-width`)
* mq-packer plugin

**Example:**

```less
.test {
  display:block;
  width: 100px;
  height: 500px;
  background: yellow;

  .respond(25rem, {
    background: green;
  });

  .respond(medium, {
    background: blue;
  });
}
```

**Expected CSS:**

```css
.test {
  display:block;
  width: 100px;
  height: 500px;
  background: yellow;
}

@media (min-width: 25rem) {
  .test {
    background: green;
  }
}

@media (min-width: 768px) {
  .test {
    background: blue;
  }
}
```

**Generated CSS:**

```css
.test {
  display:block;
  width: 100px;
  height: 500px;
  background: yellow;
}

@media (min-width: 768px) {
  .test {
    background: blue;
  }
}

@media (min-width: 25rem) {
  .test {
    background: green;
  }
}
```
