### ISSUE TITLE
Some mixins are defined within blocks

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#652]
I just found some file which define mixins inside the block.
They seem to be strongly connected, though I would prefer to encapsulate them in a separate mixin file.

**/scss/style/blocks/autocomplete.scss**
````scss
@mixin autocomplete__suggestions__item--selected {
  background-color: $color-light-blue;
  color: $color-white;
}
````

**/scss/style/blocks/control.scss**
````scss
@mixin control {
  display: block;

  width: 100%;
  height: 40px;
  border: none;
  padding-left: 13px;
  padding-right: 13px;

  line-height: 36px;

  background: $color-gray--lighter;
  color: black;
  border-radius: 0;
}

.control {
  @include control;
}

@mixin control--input {
  border: $focus-border-width solid $color-gray--lighter;
  -webkit-appearance: none;

  &.has-error {
    border-color: #ff0000;
  }

  &:focus {
    border-color: $color-light-blue;
    outline: none;
  }
}

.control--input {
  @include control--input;
}

@mixin control--short {
  max-width: 160px;
}

.control--short {
  @include control--short;
}

@mixin control--condensed {
  height: $control-height-condensed;
  line-height: $control-height-condensed;
  font-size: 14px;
}
````

**/scss/style/blocks/datepicker.scss**
````scss
@mixin make-picker-cell {
  display: table-cell;

  height: 32px;
  width: 31px;
  padding: 0;
  border: 3px solid $color-gray--dark;

  text-align: center;
  vertical-align: middle;
}
````

**/scss/style/blocks/link.scss**
````scss
@mixin link {
  color: $color-blue;
  text-decoration: underline;
  cursor: pointer;

  &:hover {
    color: $color-red;
  }
}
````

**/scss/style/blocks/modal.scss**
````scss
@mixin make-center {
  width: 780px;
  margin: 0 auto;
}
````

**/scss/style/blocks/notifications.scss**
````scss
@mixin make-notification__item-colors($color, $icon-color: white) {
  border-color: $color;

  .notifications__item__icon-container{
    background: $color;
    color: $icon-color;
  }
}
````

**/scss/style/blocks/table.scss**
````scss
@mixin make-ie9-block($display) {
  @extend .clearfix;

  display: block;
  float: left;
  clear: left;

  box-sizing: border-box;
  width: 100%;

  @include respond(medium) {
    display: $display;
    float: none;
    clear: none;

    &::after {
      display: none;
    }
  }
}
````
