### ISSUE TITLE
Sass one time imports

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#666]
This is **super** IMPORTANT.

Sass literally `@imports` all files as many times as they are imported...
Yes this issue is known - see https://github.com/sass/sass/issues/139

see Ref http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import

Related/Duplicate issues:
https://github.com/sass/sass/issues/156
http://pastebin.com/ggCMtuH2
http://stackoverflow.com/questions/36926521/webpack-sass-loader-cannot-dedupe-common-scss-imports

**foo.scss**
````scss
.foo {
  color: blue;
}
````

**app.scss**
````scss
@import 'foo';
@import 'foo';
````

**app.css**
````css
.foo {
  color: blue;
}

.foo {
  color: blue;
}
````

# Possible Workarounds

* https://github.com/wilsonpage/sass-import-once
* http://paul.wellnerbou.de/2015/05/18/avoid-multiple-imports-of-the-same-scss-file-with-sass/
* http://inside.unbounce.com/product-dev/handling-code-duplication/
